server.document-root = "/var/empty"

server.errorlog = "/home/user/src/milahu/opensubtitles-scraper/docs/wsgi/lighttpd.error.log"

server.port = 9592

# bind to this IP address
#server.bind = "10.0.10.19"

server.modules += ( "mod_proxy" )

# use the get-subs.py script's "def application" as the WSGI request handler
# gunicorn --preload --workers 4 --bind unix:"$PWD"/docs/wsgi/get-subs.sock get-subs:application
# gunicorn --preload --workers 4 --bind unix:/run/get-subs.sock get-subs:application

$HTTP["url"] =~ "^/bin/get-subtitles" {
  proxy.server = (
    "" => (
      (
        "socket" => "/home/user/src/milahu/opensubtitles-scraper/docs/wsgi/get-subs.sock"
        # "socket" => "/run/get-subs.sock"
      )
    )
  )
}

# buffer responses and send them in one part with "Content-Length: 12345" header
#server.stream-response-body = 0
# stream responses from the backend CGI with "Transfer-Encoding: chunked" header
server.stream-response-body = 1
# perform minimal buffering and potentially block the backend producer
# if the client or network is slower than the producer
#server.stream-response-body = 2
