# TODO these limits apply only to private repos?

# https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes
# Product | Storage | Minutes (per month)
# 500 MB | 2,000

# https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates
# Per-minute rates
# Operating system | Cores | Per-minute rate (USD)
# Linux | 2 | $0.008

# https://github.com/pricing/calculator?feature=actions

# action runs for 30 seconds, so 1 minute is billed
# action runs every 10 minutes, so 24*6 = 144 runs per day
# 144 minutes per day = 4320 minutes per month

# 2000 minutes per 31 days = 64.5 minutes per day
# = 2.688 minutes per hour
# = 1 minute every 22.32 minutes
# 1 minute every 23 minutes = 1940.86 minutes / 31 days

name: "fetch-subs"
on:
  workflow_dispatch:
  schedule:
    # 2000 new subs every day
    # 83.3 new subs every hour
    # 30 new subs every 21.6 minutes # rate limit: 30 requests
    # 21 new subs every 15 minutes
    # 14 new subs every 10 minutes
    # 7 new subs every 5 minutes
    # run every 5 minutes:
    #- cron:  '*/5 * * * *'
    # run every 10 minutes:
    - cron:  '*/10 * * * *'
    # run every 20 minutes:
    #- cron:  '*/20 * * * *'
    # run every 30 minutes:
    #- cron:  '*/30 * * * *'
  push:
    branches:
      - main
      - test
jobs:
  fetch_subs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: new-subs-pull.py
      run: ./new-subs-pull.py
      env:
        NEW_SUBS_REPO_URL: '${{ secrets.NEW_SUBS_REPO_URL }}'
        GIT_AUTHOR_NAME: "Milan Hauth"
        GIT_AUTHOR_EMAIL: "milahu@gmail.com"
        GIT_COMMITTER_NAME: "Milan Hauth"
        GIT_COMMITTER_EMAIL: "milahu@gmail.com"
    - name: fetch-subs.py
      run: ./fetch-subs.py --num-downloads 15-45 --first-num 9539186
    - name: new-subs-push.py
      run: ./new-subs-push.py
      env:
        NEW_SUBS_REPO_URL: '${{ secrets.NEW_SUBS_REPO_URL }}'
        GIT_AUTHOR_NAME: "Milan Hauth"
        GIT_AUTHOR_EMAIL: "milahu@gmail.com"
        GIT_COMMITTER_NAME: "Milan Hauth"
        GIT_COMMITTER_EMAIL: "milahu@gmail.com"
