name: "fetch-subs"
on:
  workflow_dispatch:
  #schedule:
    # 2000 new subs every day
    # 83.3 new subs every hour
    # 30 new subs every 21.6 minutes # rate limit: 30 requests
    # 21 new subs every 15 minutes
    # 14 new subs every 10 minutes
    # 7 new subs every 5 minutes
    # run every 10 minutes:
    #- cron:  '*/10 * * * *'
    # run every 20 minutes:
    #- cron:  '*/20 * * * *'
  push:
    branches:
      - main
      - test
jobs:
  fetch_subs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        # latest stable version of python 3
        python-version: '3.x'
        #python-version-file: '.python-version'
        # cache pip dependencies
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: debug-before
      run: bash -c "set -x; ls -l"
    - name: 'pull new-subs'
      run: git clone --depth=1 $NEW_SUBS_REPO_URL new-subs
      env:
        NEW_SUBS_REPO_URL: '${{ secrets.NEW_SUBS_REPO_URL }}'
    - name: fetch-subs.py
      run: ./fetch-subs.py --num-downloads 3 --first-num 9539186
      # https://github.com/your_name/your_repo/settings/secrets/actions
      #env:
      #  API_TOKEN_GITHUB: '${{ secrets.API_TOKEN_GITHUB }}'
      #  API_USER_GITHUB: '${{ secrets.API_USER_GITHUB }}'
    - name: debug-after
      run: bash -c "set -x; ls -l; ls -l new-subs/"
    - name: 'push new-subs'
      run: |
        bash -c '

        export GIT_AUTHOR_NAME="Milan Hauth"
        export GIT_AUTHOR_EMAIL="milahu@gmail.com"
        export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
        export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL

        git -C new-subs add "*"
        git -C new-subs commit -m up
        git -C new-subs push $NEW_SUBS_REPO_URL
        '
      env:
        NEW_SUBS_REPO_URL: '${{ secrets.NEW_SUBS_REPO_URL }}'
        #API_TOKEN_GITHUB: '${{ secrets.API_TOKEN_GITHUB }}'
        #API_USER_GITHUB: '${{ secrets.API_USER_GITHUB }}'
    #- name: store-subs.py
    #  run: ./store-subs.py
