name: "fetch-subs"
on:
  workflow_dispatch:
  schedule:
    # 2000 new subs every day
    # 83.3 new subs every hour
    # 30 new subs every 21.6 minutes # rate limit: 30 requests
    # 21 new subs every 15 minutes
    # 14 new subs every 10 minutes
    # 7 new subs every 5 minutes
    # run every 5 minutes:
    #- cron:  '*/5 * * * *'
    # run every 10 minutes:
    - cron:  '*/10 * * * *'
    # run every 20 minutes:
    #- cron:  '*/20 * * * *'
  push:
    branches:
      - main
      - test
jobs:
  fetch_subs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: new-subs-pull.py
      run: ./new-subs-pull.py
      env:
        NEW_SUBS_REPO_URL: '${{ secrets.NEW_SUBS_REPO_URL }}'
        GIT_AUTHOR_NAME: "Milan Hauth"
        GIT_AUTHOR_EMAIL: "milahu@gmail.com"
        GIT_COMMITTER_NAME: "Milan Hauth"
        GIT_COMMITTER_EMAIL: "milahu@gmail.com"
    - name: fetch-subs.py
      run: ./fetch-subs.py --num-downloads 25 --first-num 9539186
    - name: new-subs-push.py
      run: ./new-subs-push.py
      env:
        NEW_SUBS_REPO_URL: '${{ secrets.NEW_SUBS_REPO_URL }}'
        GIT_AUTHOR_NAME: "Milan Hauth"
        GIT_AUTHOR_EMAIL: "milahu@gmail.com"
        GIT_COMMITTER_NAME: "Milan Hauth"
        GIT_COMMITTER_EMAIL: "milahu@gmail.com"
